# Generated by Django 6.0.3 on 2026-03-27 07:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("themes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="themeconfiguration",
            name="logo",
        ),
    ]
