# Generated by Django 6.0.3 on 2026-03-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("themes", "0002_remove_themeconfiguration_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="themeconfiguration",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Tenant logo image",
                null=True,
                upload_to="tenant_logos/",
            ),
        ),
    ]
