# Generated by Django 6.0.3 on 2026-03-27 08:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("themes", "0003_themeconfiguration_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="themeconfiguration",
            name="navbar_color",
            field=models.CharField(
                default="#1F2937",
                help_text="Navbar background color",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid hex color code (e.g., #FF5733 or #F57)",
                        regex="^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$",
                    )
                ],
            ),
        ),
    ]
