# Generated by Django 5.2.5 on 2025-09-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Supliers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=20)),
                ("address", models.TextField()),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "supliers",
            },
        ),
    ]
