# Generated by Django 6.0.3 on 2026-03-26 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Supliers", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supliers",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant this supplier belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suppliers",
                to="tenants.tenant",
            ),
        ),
    ]
