# Generated by Django 5.2.5 on 2025-09-14 10:20

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Supliers", "0001_initial"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="is_deleted",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the category is deleted (soft delete).",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_expired_applicable",
            field=models.BooleanField(
                default=False, help_text="Does this category require expiry dates?"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(help_text="Name of the category.", max_length=100),
        ),
        migrations.AlterField(
            model_name="productstock",
            name="base_unit",
            field=models.ForeignKey(
                blank=True,
                help_text="Base unit type for this product.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products_base_unit",
                to="inventory.unittype",
            ),
        ),
        migrations.AlterField(
            model_name="productstock",
            name="batch_number",
            field=models.CharField(
                blank=True,
                help_text="Batch number for the product.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="productstock",
            name="category",
            field=models.ForeignKey(
                help_text="Category of the product.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="inventory.category",
            ),
        ),
        migrations.AlterField(
            model_name="productstock",
            name="cost_price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Cost price of the product.",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="productstock",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Expiry date of the product, if applicable.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="productstock",
            name="is_deleted",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the product is deleted (soft delete).",
            ),
        ),
        migrations.AlterField(
            model_name="productstock",
            name="margin",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Margin for the product.",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="productstock",
            name="name",
            field=models.CharField(help_text="Product name.", max_length=100),
        ),
        migrations.AlterField(
            model_name="productstock",
            name="product_code",
            field=models.CharField(
                blank=True,
                help_text="Unique product code.",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="productstock",
            name="serial_number",
            field=models.CharField(
                blank=True,
                help_text="Serial number for the product.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="productstock",
            name="stock",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Current stock quantity.",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="productstock",
            name="supliers",
            field=models.ForeignKey(
                blank=True,
                help_text="Supplier for this product.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="Supliers.supliers",
            ),
        ),
        migrations.AlterField(
            model_name="productstock",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                help_text="Unit type for this product.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.unittype",
            ),
        ),
        migrations.AlterField(
            model_name="unittype",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Optional description of the unit type.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="unittype",
            name="is_deleted",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the unit type is deleted (soft delete).",
            ),
        ),
        migrations.AlterField(
            model_name="unittype",
            name="unit",
            field=models.CharField(
                help_text="Name of the unit, e.g., 'Piece', 'Box', 'Carton'.",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="unittypeconfigurations",
            name="conversion_per_unit",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                help_text="Number of conversion units per unit type.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="unittypeconfigurations",
            name="conversion_unit_name",
            field=models.ForeignKey(
                blank=True,
                help_text="Unit name to convert to, e.g., 'pieces', 'boxes'.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversion_unit_configurations",
                to="inventory.unittype",
            ),
        ),
        migrations.AlterField(
            model_name="unittypeconfigurations",
            name="is_deleted",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the configuration is deleted (soft delete).",
            ),
        ),
        migrations.AlterField(
            model_name="unittypeconfigurations",
            name="product",
            field=models.ForeignKey(
                blank=True,
                help_text="Product for which this configuration applies.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.productstock",
            ),
        ),
        migrations.AlterField(
            model_name="unittypeconfigurations",
            name="unit_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Unit type for conversion.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="configUnit_type",
                to="inventory.unittype",
            ),
        ),
    ]
