# Generated by Django 5.2.5 on 2025-09-19 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_category_is_deleted_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="unittypeconfigurations",
            old_name="unit_type",
            new_name="base_unit",
        ),
    ]
