# Generated by Django 5.2.5 on 2025-09-23 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_rename_unit_type_unittypeconfigurations_base_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unittypeconfigurations",
            name="base_unit",
            field=models.ForeignKey(
                blank=True,
                help_text="Unit type for conversion.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="configurations",
                to="inventory.unittype",
            ),
        ),
    ]
