# Generated by Django 6.0.3 on 2026-03-26 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_rename_unit_type_unittypeconfigurations_base_unit"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant this category belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="productstock",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant this product belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="unittype",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant this unit type belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unit_types",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="unittypeconfigurations",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant this configuration belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unit_configurations",
                to="tenants.tenant",
            ),
        ),
    ]
