# Generated by Django 5.2.5 on 2025-09-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingitem",
            name="quantity",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
